### ISSUE TITLE
Reservation is sometimes null when trying to cancel

### ISSUE THREAD

**Issue by ptesavol** [ubikampus/reservator#99]
The app sometimes crashes when cancelling a reservation. Could it be that the same reservation is being cancelled twice? Stack trace below:

 --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.futurice.android.reservator.debug, PID: 4415
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.futurice.android.reservator.model.Reservation.isCancellable()' on a null object reference
        at com.futurice.android.reservator.model.platformcalendar.PlatformCalendarDataProxy.cancelReservation(PlatformCalendarDataProxy.java:205)
        at com.futurice.android.reservator.view.trafficlights.TrafficLightsPresenter.cancelCurrentReservation(TrafficLightsPresenter.java:133)
        at com.futurice.android.reservator.view.trafficlights.TrafficLightsPresenter.onReservationMinutesChanged(TrafficLightsPresenter.java:202)
        at com.futurice.android.reservator.view.trafficlights.OngoingReservationFragment.saveChanges(OngoingReservationFragment.java:110)
        at com.futurice.android.reservator.view.trafficlights.OngoingReservationFragment.onChangeCountDownFinished(OngoingReservationFragment.java:173)
        at com.futurice.android.reservator.view.trafficlights.OngoingReservationFragment$3.onFinish(OngoingReservationFragment.java:207)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ptesavol** [comment]
I fixed this simply by adding a null-check. No time to start looking for the root cause.
